/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const users_sessions = sqliteTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = sqliteTable(
  "media",
  {
    id: integer("id").primaryKey(),
    alt: text("alt").notNull(),
    creditText: text("credit_text").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text("url"),
    thumbnailURL: text("thumbnail_u_r_l"),
    filename: text("filename"),
    mimeType: text("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const blog = sqliteTable(
  "blog",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    shortDescription: text("short_description"),
    content: text("content", { mode: "json" }).notNull(),
    thumbnailImage: integer("thumbnail_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    publishedAt: text("published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    author: integer("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("blog_thumbnail_image_idx").on(columns.thumbnailImage),
    index("blog_author_idx").on(columns.author),
    index("blog_updated_at_idx").on(columns.updatedAt),
    index("blog_created_at_idx").on(columns.createdAt),
  ],
);

export const projects_images = sqliteTable(
  "projects_images",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("projects_images_order_idx").on(columns._order),
    index("projects_images_parent_id_idx").on(columns._parentID),
    index("projects_images_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [projects.id],
      name: "projects_images_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const projects = sqliteTable(
  "projects",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    description: text("description"),
    thumbnailImage: integer("thumbnail_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    publishedAt: text("published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    client: text("client").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("projects_thumbnail_image_idx").on(columns.thumbnailImage),
    index("projects_updated_at_idx").on(columns.updatedAt),
    index("projects_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    blogID: integer("blog_id"),
    projectsID: integer("projects_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_blog_id_idx").on(columns.blogID),
    index("payload_locked_documents_rels_projects_id_idx").on(
      columns.projectsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blogID"]],
      foreignColumns: [blog.id],
      name: "payload_locked_documents_rels_blog_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["projectsID"]],
      foreignColumns: [projects.id],
      name: "payload_locked_documents_rels_projects_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const company = sqliteTable(
  "company",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    description: text("description").notNull(),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    email: text("email"),
    phone: text("phone"),
    website: text("website"),
    address_line1: text("address_line1"),
    address_line2: text("address_line2"),
    address_city: text("address_city"),
    address_state: text("address_state"),
    address_postalCode: text("address_postal_code"),
    address_country: text("address_country"),
    social_facebook: text("social_facebook"),
    social_twitter: text("social_twitter"),
    social_linkedin: text("social_linkedin"),
    social_instagram: text("social_instagram"),
    social_github: text("social_github"),
    social_youtube: text("social_youtube"),
    updatedAt: text("updated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [index("company_logo_idx").on(columns.logo)],
);

export const footer_footer_groups_urls = sqliteTable(
  "footer_footer_groups_urls",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("footer_footer_groups_urls_order_idx").on(columns._order),
    index("footer_footer_groups_urls_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer_footer_groups.id],
      name: "footer_footer_groups_urls_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer_footer_groups = sqliteTable(
  "footer_footer_groups",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    title: text("title").notNull(),
  },
  (columns) => [
    index("footer_footer_groups_order_idx").on(columns._order),
    index("footer_footer_groups_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_footer_groups_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer = sqliteTable("footer", {
  id: integer("id").primaryKey(),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const header_links = sqliteTable(
  "header_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("header_links_order_idx").on(columns._order),
    index("header_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [header.id],
      name: "header_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const header = sqliteTable("header", {
  id: integer("id").primaryKey(),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const legal_pages = sqliteTable("legal_pages", {
  id: integer("id").primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").notNull(),
  content: text("content", { mode: "json" }).notNull(),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_blog = relations(blog, ({ one }) => ({
  thumbnailImage: one(media, {
    fields: [blog.thumbnailImage],
    references: [media.id],
    relationName: "thumbnailImage",
  }),
  author: one(users, {
    fields: [blog.author],
    references: [users.id],
    relationName: "author",
  }),
}));
export const relations_projects_images = relations(
  projects_images,
  ({ one }) => ({
    _parentID: one(projects, {
      fields: [projects_images._parentID],
      references: [projects.id],
      relationName: "images",
    }),
    image: one(media, {
      fields: [projects_images.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_projects = relations(projects, ({ one, many }) => ({
  thumbnailImage: one(media, {
    fields: [projects.thumbnailImage],
    references: [media.id],
    relationName: "thumbnailImage",
  }),
  images: many(projects_images, {
    relationName: "images",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    blogID: one(blog, {
      fields: [payload_locked_documents_rels.blogID],
      references: [blog.id],
      relationName: "blog",
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: "projects",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_company = relations(company, ({ one }) => ({
  logo: one(media, {
    fields: [company.logo],
    references: [media.id],
    relationName: "logo",
  }),
}));
export const relations_footer_footer_groups_urls = relations(
  footer_footer_groups_urls,
  ({ one }) => ({
    _parentID: one(footer_footer_groups, {
      fields: [footer_footer_groups_urls._parentID],
      references: [footer_footer_groups.id],
      relationName: "urls",
    }),
  }),
);
export const relations_footer_footer_groups = relations(
  footer_footer_groups,
  ({ one, many }) => ({
    _parentID: one(footer, {
      fields: [footer_footer_groups._parentID],
      references: [footer.id],
      relationName: "footerGroups",
    }),
    urls: many(footer_footer_groups_urls, {
      relationName: "urls",
    }),
  }),
);
export const relations_footer = relations(footer, ({ many }) => ({
  footerGroups: many(footer_footer_groups, {
    relationName: "footerGroups",
  }),
}));
export const relations_header_links = relations(header_links, ({ one }) => ({
  _parentID: one(header, {
    fields: [header_links._parentID],
    references: [header.id],
    relationName: "links",
  }),
}));
export const relations_header = relations(header, ({ many }) => ({
  links: many(header_links, {
    relationName: "links",
  }),
}));
export const relations_legal_pages = relations(legal_pages, () => ({}));

type DatabaseSchema = {
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  blog: typeof blog;
  projects_images: typeof projects_images;
  projects: typeof projects;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  company: typeof company;
  footer_footer_groups_urls: typeof footer_footer_groups_urls;
  footer_footer_groups: typeof footer_footer_groups;
  footer: typeof footer;
  header_links: typeof header_links;
  header: typeof header;
  legal_pages: typeof legal_pages;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_blog: typeof relations_blog;
  relations_projects_images: typeof relations_projects_images;
  relations_projects: typeof relations_projects;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_company: typeof relations_company;
  relations_footer_footer_groups_urls: typeof relations_footer_footer_groups_urls;
  relations_footer_footer_groups: typeof relations_footer_footer_groups;
  relations_footer: typeof relations_footer;
  relations_header_links: typeof relations_header_links;
  relations_header: typeof relations_header;
  relations_legal_pages: typeof relations_legal_pages;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
