/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-sqlite";
import {
  sqliteTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  text,
  numeric,
} from "@payloadcms/db-sqlite/drizzle/sqlite-core";
import { sql, relations } from "@payloadcms/db-sqlite/drizzle";

export const users_sessions = sqliteTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    expiresAt: text("expires_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = sqliteTable(
  "users",
  {
    id: integer("id").primaryKey(),
    displayName: text("display_name").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    email: text("email").notNull(),
    resetPasswordToken: text("reset_password_token"),
    resetPasswordExpiration: text("reset_password_expiration").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    salt: text("salt"),
    hash: text("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: text("lock_until").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = sqliteTable(
  "media",
  {
    id: integer("id").primaryKey(),
    alt: text("alt").notNull(),
    creditText: text("credit_text").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    url: text("url"),
    thumbnailURL: text("thumbnail_u_r_l"),
    filename: text("filename"),
    mimeType: text("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const blog = sqliteTable(
  "blog",
  {
    id: integer("id").primaryKey(),
    title: text("title"),
    generateSlug: integer("generate_slug", { mode: "boolean" }).default(true),
    slug: text("slug"),
    shortDescription: text("short_description"),
    author: integer("author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    thumbnailImage: integer("thumbnail_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    publishedAt: text("published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    category: text("category", {
      enum: ["blog-post", "case-study", "success-story"],
    }),
    content: text("content", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    _status: text("_status", { enum: ["draft", "published"] }).default("draft"),
  },
  (columns) => [
    uniqueIndex("blog_slug_idx").on(columns.slug),
    index("blog_author_idx").on(columns.author),
    index("blog_thumbnail_image_idx").on(columns.thumbnailImage),
    index("blog_updated_at_idx").on(columns.updatedAt),
    index("blog_created_at_idx").on(columns.createdAt),
    index("blog__status_idx").on(columns._status),
  ],
);

export const _blog_v = sqliteTable(
  "_blog_v",
  {
    id: integer("id").primaryKey(),
    parent: integer("parent_id").references(() => blog.id, {
      onDelete: "set null",
    }),
    version_title: text("version_title"),
    version_generateSlug: integer("version_generate_slug", {
      mode: "boolean",
    }).default(true),
    version_slug: text("version_slug"),
    version_shortDescription: text("version_short_description"),
    version_author: integer("version_author_id").references(() => users.id, {
      onDelete: "set null",
    }),
    version_thumbnailImage: integer("version_thumbnail_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_publishedAt: text("version_published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version_category: text("version_category", {
      enum: ["blog-post", "case-study", "success-story"],
    }),
    version_content: text("version_content", { mode: "json" }),
    version_updatedAt: text("version_updated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version_createdAt: text("version_created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    version__status: text("version__status", {
      enum: ["draft", "published"],
    }).default("draft"),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    latest: integer("latest", { mode: "boolean" }),
  },
  (columns) => [
    index("_blog_v_parent_idx").on(columns.parent),
    index("_blog_v_version_version_slug_idx").on(columns.version_slug),
    index("_blog_v_version_version_author_idx").on(columns.version_author),
    index("_blog_v_version_version_thumbnail_image_idx").on(
      columns.version_thumbnailImage,
    ),
    index("_blog_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_blog_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_blog_v_version_version__status_idx").on(columns.version__status),
    index("_blog_v_created_at_idx").on(columns.createdAt),
    index("_blog_v_updated_at_idx").on(columns.updatedAt),
    index("_blog_v_latest_idx").on(columns.latest),
  ],
);

export const products_images = sqliteTable(
  "products_images",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("products_images_order_idx").on(columns._order),
    index("products_images_parent_id_idx").on(columns._parentID),
    index("products_images_image_idx").on(columns.image),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [products.id],
      name: "products_images_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const products = sqliteTable(
  "products",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    generateSlug: integer("generate_slug", { mode: "boolean" }).default(true),
    slug: text("slug").notNull(),
    description: text("description"),
    thumbnailImage: integer("thumbnail_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    publishedAt: text("published_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    client: text("client").notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("products_slug_idx").on(columns.slug),
    index("products_thumbnail_image_idx").on(columns.thumbnailImage),
    index("products_updated_at_idx").on(columns.updatedAt),
    index("products_created_at_idx").on(columns.createdAt),
  ],
);

export const services = sqliteTable(
  "services",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    generateSlug: integer("generate_slug", { mode: "boolean" }).default(true),
    slug: text("slug").notNull(),
    description: text("description"),
    illustration: integer("illustration_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("services_slug_idx").on(columns.slug),
    index("services_illustration_idx").on(columns.illustration),
    index("services_updated_at_idx").on(columns.updatedAt),
    index("services_created_at_idx").on(columns.createdAt),
  ],
);

export const services_rels = sqliteTable(
  "services_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    productsID: integer("products_id"),
  },
  (columns) => [
    index("services_rels_order_idx").on(columns.order),
    index("services_rels_parent_idx").on(columns.parent),
    index("services_rels_path_idx").on(columns.path),
    index("services_rels_products_id_idx").on(columns.productsID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [services.id],
      name: "services_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["productsID"]],
      foreignColumns: [products.id],
      name: "services_rels_products_fk",
    }).onDelete("cascade"),
  ],
);

export const legal_pages = sqliteTable(
  "legal_pages",
  {
    id: integer("id").primaryKey(),
    title: text("title").notNull(),
    generateSlug: integer("generate_slug", { mode: "boolean" }).default(true),
    slug: text("slug").notNull(),
    content: text("content", { mode: "json" }).notNull(),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    uniqueIndex("legal_pages_slug_idx").on(columns.slug),
    index("legal_pages_updated_at_idx").on(columns.updatedAt),
    index("legal_pages_created_at_idx").on(columns.createdAt),
  ],
);

export const submissions = sqliteTable(
  "submissions",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    company: text("company"),
    message: text("message").notNull(),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [index("submissions_updated_at_idx").on(columns.updatedAt)],
);

export const payload_kv = sqliteTable(
  "payload_kv",
  {
    id: integer("id").primaryKey(),
    key: text("key").notNull(),
    data: text("data", { mode: "json" }).notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = sqliteTable(
  "payload_locked_documents",
  {
    id: integer("id").primaryKey(),
    globalSlug: text("global_slug"),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = sqliteTable(
  "payload_locked_documents_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    blogID: integer("blog_id"),
    productsID: integer("products_id"),
    servicesID: integer("services_id"),
    "legal-pagesID": integer("legal_pages_id"),
    submissionsID: integer("submissions_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_blog_id_idx").on(columns.blogID),
    index("payload_locked_documents_rels_products_id_idx").on(
      columns.productsID,
    ),
    index("payload_locked_documents_rels_services_id_idx").on(
      columns.servicesID,
    ),
    index("payload_locked_documents_rels_legal_pages_id_idx").on(
      columns["legal-pagesID"],
    ),
    index("payload_locked_documents_rels_submissions_id_idx").on(
      columns.submissionsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["blogID"]],
      foreignColumns: [blog.id],
      name: "payload_locked_documents_rels_blog_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["productsID"]],
      foreignColumns: [products.id],
      name: "payload_locked_documents_rels_products_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["servicesID"]],
      foreignColumns: [services.id],
      name: "payload_locked_documents_rels_services_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["legal-pagesID"]],
      foreignColumns: [legal_pages.id],
      name: "payload_locked_documents_rels_legal_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["submissionsID"]],
      foreignColumns: [submissions.id],
      name: "payload_locked_documents_rels_submissions_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = sqliteTable(
  "payload_preferences",
  {
    id: integer("id").primaryKey(),
    key: text("key"),
    value: text("value", { mode: "json" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = sqliteTable(
  "payload_preferences_rels",
  {
    id: integer("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: text("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = sqliteTable(
  "payload_migrations",
  {
    id: integer("id").primaryKey(),
    name: text("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: text("updated_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
    createdAt: text("created_at")
      .notNull()
      .default(sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const company = sqliteTable(
  "company",
  {
    id: integer("id").primaryKey(),
    name: text("name").notNull(),
    description: text("description").notNull(),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    email: text("email"),
    phone: text("phone"),
    website: text("website"),
    contactUsUrl: text("contact_us_url").notNull(),
    address_line1: text("address_line1"),
    address_line2: text("address_line2"),
    address_city: text("address_city"),
    address_state: text("address_state"),
    address_postalCode: text("address_postal_code"),
    address_country: text("address_country"),
    social_facebook: text("social_facebook"),
    social_twitter: text("social_twitter"),
    social_linkedin: text("social_linkedin"),
    social_instagram: text("social_instagram"),
    social_github: text("social_github"),
    social_youtube: text("social_youtube"),
    updatedAt: text("updated_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
    createdAt: text("created_at").default(
      sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
    ),
  },
  (columns) => [index("company_logo_idx").on(columns.logo)],
);

export const footer_footer_groups_urls = sqliteTable(
  "footer_footer_groups_urls",
  {
    _order: integer("_order").notNull(),
    _parentID: text("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("footer_footer_groups_urls_order_idx").on(columns._order),
    index("footer_footer_groups_urls_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer_footer_groups.id],
      name: "footer_footer_groups_urls_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer_footer_groups = sqliteTable(
  "footer_footer_groups",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    title: text("title").notNull(),
  },
  (columns) => [
    index("footer_footer_groups_order_idx").on(columns._order),
    index("footer_footer_groups_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_footer_groups_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer = sqliteTable("footer", {
  id: integer("id").primaryKey(),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const header_links = sqliteTable(
  "header_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    label: text("label").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("header_links_order_idx").on(columns._order),
    index("header_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [header.id],
      name: "header_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const header = sqliteTable("header", {
  id: integer("id").primaryKey(),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const site_info_backed_by_backers = sqliteTable(
  "site_info_backed_by_backers",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    logo: integer("logo_id")
      .notNull()
      .references(() => media.id, {
        onDelete: "set null",
      }),
    name: text("name").notNull(),
    url: text("url").notNull(),
  },
  (columns) => [
    index("site_info_backed_by_backers_order_idx").on(columns._order),
    index("site_info_backed_by_backers_parent_id_idx").on(columns._parentID),
    index("site_info_backed_by_backers_logo_idx").on(columns.logo),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_info.id],
      name: "site_info_backed_by_backers_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_info_services_services = sqliteTable(
  "site_info_services_services",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    title: text("title").notNull(),
    description: text("description").notNull(),
    illustration: integer("illustration_id").references(() => media.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    index("site_info_services_services_order_idx").on(columns._order),
    index("site_info_services_services_parent_id_idx").on(columns._parentID),
    index("site_info_services_services_illustration_idx").on(
      columns.illustration,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_info.id],
      name: "site_info_services_services_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_info_faq_faq_items = sqliteTable(
  "site_info_faq_faq_items",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: text("id").primaryKey(),
    question: text("question").notNull(),
    answer: text("answer").notNull(),
  },
  (columns) => [
    index("site_info_faq_faq_items_order_idx").on(columns._order),
    index("site_info_faq_faq_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_info.id],
      name: "site_info_faq_faq_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_info = sqliteTable("site_info", {
  id: integer("id").primaryKey(),
  title: text("title").notNull(),
  subtitle: text("subtitle").notNull(),
  contactUsUrl: text("contact_us_url").notNull(),
  backedBy_title: text("backed_by_title").notNull(),
  backedBy_description: text("backed_by_description").notNull(),
  services_title: text("services_title").notNull(),
  services_description: text("services_description").notNull(),
  faq_title: text("faq_title").notNull(),
  faq_description: text("faq_description").notNull(),
  updatedAt: text("updated_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
  createdAt: text("created_at").default(
    sql`(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))`,
  ),
});

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_blog = relations(blog, ({ one }) => ({
  author: one(users, {
    fields: [blog.author],
    references: [users.id],
    relationName: "author",
  }),
  thumbnailImage: one(media, {
    fields: [blog.thumbnailImage],
    references: [media.id],
    relationName: "thumbnailImage",
  }),
}));
export const relations__blog_v = relations(_blog_v, ({ one }) => ({
  parent: one(blog, {
    fields: [_blog_v.parent],
    references: [blog.id],
    relationName: "parent",
  }),
  version_author: one(users, {
    fields: [_blog_v.version_author],
    references: [users.id],
    relationName: "version_author",
  }),
  version_thumbnailImage: one(media, {
    fields: [_blog_v.version_thumbnailImage],
    references: [media.id],
    relationName: "version_thumbnailImage",
  }),
}));
export const relations_products_images = relations(
  products_images,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_images._parentID],
      references: [products.id],
      relationName: "images",
    }),
    image: one(media, {
      fields: [products_images.image],
      references: [media.id],
      relationName: "image",
    }),
  }),
);
export const relations_products = relations(products, ({ one, many }) => ({
  thumbnailImage: one(media, {
    fields: [products.thumbnailImage],
    references: [media.id],
    relationName: "thumbnailImage",
  }),
  images: many(products_images, {
    relationName: "images",
  }),
}));
export const relations_services_rels = relations(services_rels, ({ one }) => ({
  parent: one(services, {
    fields: [services_rels.parent],
    references: [services.id],
    relationName: "_rels",
  }),
  productsID: one(products, {
    fields: [services_rels.productsID],
    references: [products.id],
    relationName: "products",
  }),
}));
export const relations_services = relations(services, ({ one, many }) => ({
  illustration: one(media, {
    fields: [services.illustration],
    references: [media.id],
    relationName: "illustration",
  }),
  _rels: many(services_rels, {
    relationName: "_rels",
  }),
}));
export const relations_legal_pages = relations(legal_pages, () => ({}));
export const relations_submissions = relations(submissions, () => ({}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    blogID: one(blog, {
      fields: [payload_locked_documents_rels.blogID],
      references: [blog.id],
      relationName: "blog",
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: "products",
    }),
    servicesID: one(services, {
      fields: [payload_locked_documents_rels.servicesID],
      references: [services.id],
      relationName: "services",
    }),
    "legal-pagesID": one(legal_pages, {
      fields: [payload_locked_documents_rels["legal-pagesID"]],
      references: [legal_pages.id],
      relationName: "legal-pages",
    }),
    submissionsID: one(submissions, {
      fields: [payload_locked_documents_rels.submissionsID],
      references: [submissions.id],
      relationName: "submissions",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_company = relations(company, ({ one }) => ({
  logo: one(media, {
    fields: [company.logo],
    references: [media.id],
    relationName: "logo",
  }),
}));
export const relations_footer_footer_groups_urls = relations(
  footer_footer_groups_urls,
  ({ one }) => ({
    _parentID: one(footer_footer_groups, {
      fields: [footer_footer_groups_urls._parentID],
      references: [footer_footer_groups.id],
      relationName: "urls",
    }),
  }),
);
export const relations_footer_footer_groups = relations(
  footer_footer_groups,
  ({ one, many }) => ({
    _parentID: one(footer, {
      fields: [footer_footer_groups._parentID],
      references: [footer.id],
      relationName: "footerGroups",
    }),
    urls: many(footer_footer_groups_urls, {
      relationName: "urls",
    }),
  }),
);
export const relations_footer = relations(footer, ({ many }) => ({
  footerGroups: many(footer_footer_groups, {
    relationName: "footerGroups",
  }),
}));
export const relations_header_links = relations(header_links, ({ one }) => ({
  _parentID: one(header, {
    fields: [header_links._parentID],
    references: [header.id],
    relationName: "links",
  }),
}));
export const relations_header = relations(header, ({ many }) => ({
  links: many(header_links, {
    relationName: "links",
  }),
}));
export const relations_site_info_backed_by_backers = relations(
  site_info_backed_by_backers,
  ({ one }) => ({
    _parentID: one(site_info, {
      fields: [site_info_backed_by_backers._parentID],
      references: [site_info.id],
      relationName: "backedBy_backers",
    }),
    logo: one(media, {
      fields: [site_info_backed_by_backers.logo],
      references: [media.id],
      relationName: "logo",
    }),
  }),
);
export const relations_site_info_services_services = relations(
  site_info_services_services,
  ({ one }) => ({
    _parentID: one(site_info, {
      fields: [site_info_services_services._parentID],
      references: [site_info.id],
      relationName: "services_services",
    }),
    illustration: one(media, {
      fields: [site_info_services_services.illustration],
      references: [media.id],
      relationName: "illustration",
    }),
  }),
);
export const relations_site_info_faq_faq_items = relations(
  site_info_faq_faq_items,
  ({ one }) => ({
    _parentID: one(site_info, {
      fields: [site_info_faq_faq_items._parentID],
      references: [site_info.id],
      relationName: "faq_faqItems",
    }),
  }),
);
export const relations_site_info = relations(site_info, ({ many }) => ({
  backedBy_backers: many(site_info_backed_by_backers, {
    relationName: "backedBy_backers",
  }),
  services_services: many(site_info_services_services, {
    relationName: "services_services",
  }),
  faq_faqItems: many(site_info_faq_faq_items, {
    relationName: "faq_faqItems",
  }),
}));

type DatabaseSchema = {
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  blog: typeof blog;
  _blog_v: typeof _blog_v;
  products_images: typeof products_images;
  products: typeof products;
  services: typeof services;
  services_rels: typeof services_rels;
  legal_pages: typeof legal_pages;
  submissions: typeof submissions;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  company: typeof company;
  footer_footer_groups_urls: typeof footer_footer_groups_urls;
  footer_footer_groups: typeof footer_footer_groups;
  footer: typeof footer;
  header_links: typeof header_links;
  header: typeof header;
  site_info_backed_by_backers: typeof site_info_backed_by_backers;
  site_info_services_services: typeof site_info_services_services;
  site_info_faq_faq_items: typeof site_info_faq_faq_items;
  site_info: typeof site_info;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_blog: typeof relations_blog;
  relations__blog_v: typeof relations__blog_v;
  relations_products_images: typeof relations_products_images;
  relations_products: typeof relations_products;
  relations_services_rels: typeof relations_services_rels;
  relations_services: typeof relations_services;
  relations_legal_pages: typeof relations_legal_pages;
  relations_submissions: typeof relations_submissions;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_company: typeof relations_company;
  relations_footer_footer_groups_urls: typeof relations_footer_footer_groups_urls;
  relations_footer_footer_groups: typeof relations_footer_footer_groups;
  relations_footer: typeof relations_footer;
  relations_header_links: typeof relations_header_links;
  relations_header: typeof relations_header;
  relations_site_info_backed_by_backers: typeof relations_site_info_backed_by_backers;
  relations_site_info_services_services: typeof relations_site_info_services_services;
  relations_site_info_faq_faq_items: typeof relations_site_info_faq_faq_items;
  relations_site_info: typeof relations_site_info;
};

declare module "@payloadcms/db-sqlite" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
